# Needed YAML tag for the configuration object
--- !<tag:barectf.org,2020/3/config>

# Configuration's trace
trace:
  # Type of the trace
  type:
    # Add standard field type aliases
    $include:
      - stdint.yaml
      - stdmisc.yaml

    # Native byte order is little-endian
    native-byte-order: little-endian

    # One clock type
    clock-types:
      # The Linux FS platform requires a clock type named `default`
      # which has a 1-GHz frequency and the `uint64_t` C type.
      default:
        frequency: 1000
        offset:
          seconds: 0
          cycles: 0
        origin-is-unix-epoch: false
        $c-type: uint64_t

    # One data stream type
    data-stream-types:
      # Stream type named `default`
      default:
        # Default data stream type
        $is-default: true
        $default-clock-type-name: default
        
        # Two event record types
        event-record-types:
          sim_finished:
            payload-field-type:
              class: structure
              members: []
          
          resched:
            payload-field-type:
              class: structure
              members: []

          proc_idle:
            payload-field-type:
              class: structure
              members:
                - cpu: int32

          proc_activated:
            payload-field-type:
              class: structure
              members:
                - cpu: int32

          serv_budget_replenished:
            payload-field-type:
              class: structure
              members:
                - tid: int32
                - budget: int64

          virtual_time:
            payload-field-type:
              class: structure
              members:
                - tid: int32
                - virtual_time: int64

          remaining_execution_time:
            payload-field-type:
              class: structure
              members:
                - tid: int32
                - remaining_execution_time: int64
              
          job_arrival:
            payload-field-type:
              class: structure
              members:
                - tid: int32
                - virtual_time: int32
                - deadline: int32

          job_finished:
            payload-field-type:
              class: structure
              members:
                - tid: int32

          serv_postpone:
            payload-field-type:
              class: structure
              members:
                - tid: int32

          serv_ready:
            payload-field-type:
              class: structure
              members:
                - tid: int32

          serv_non_cont:
            payload-field-type:
              class: structure
              members:
                - tid: int32

          serv_budget_exhausted:
            payload-field-type:
              class: structure
              members:
                - tid: int32

          serv_inactive:
            payload-field-type:
              class: structure
              members:
                - tid: int32  

          serv_running:
            payload-field-type:
              class: structure
              members:
                - tid: int32

          task_preempted:
            payload-field-type:
              class: structure
              members:
                - tid: int32

          task_scheduled:
            payload-field-type:
              class: structure
              members:
                - cpu: int32

          task_rejected:
            payload-field-type:
              class: structure
              members:
                - tid: int32
